### ISSUE TITLE
Please don't use --classic with snap install

### ISSUE THREAD

**Issue by popey** [sigoden/upt#35]
Snaps come in various confinement levels. Most common are `strict`, `classic` and (sometimes) `devmode`. The majority are `strict` and so are confined, such that the application cannot access things outside the approved interfaces such as `home`, `network`, and `camera`.

A `classic` snap has no such confinement, and can access all files on the computer. 

When using `snap install`, if the user selects a `classic` snap, they will be informed of this fact, with this message:

```bash
alan@nuc:~$ snap install code
error: This revision of snap "code" was published using classic confinement and
       thus may perform arbitrary system changes outside of the security
       sandbox that snaps are usually confined to, which may put your system at
       risk.

       If you understand and want to proceed repeat the command including
       --classic.
```

*If* and only *if* the user decides they want to take the risk of installing the snap, they can optionally choose to install the snap by adding the `--classic` option. 

`upt` pre-fills `--classic` on every snap install, whether the user asked or not. Even worse, it only actually shows its own warning about `classic` snaps on *non* classic snaps! 

This is not a good way to implement snap installation. `upt` should ideally show the user the message above, and allow them the choice to use the `--classic` option or not.

**Comment by sigoden** [comment]
A large number of commonly used snaps require `--classic`. I think there is nothing wrong with the current default `classic ` installation strategy.

upt is just a wrapper. People who are really proficient in `snap` are not likely to use it. For people who use `upt install` other than `snap install`, I think they prefer that you directly install what they want instead of throwing an error for them to study.
